import type { SanitizationOptions } from "../types.js";

export const DEFAULT_ALLOWED_PROPERTIES = [
  "align-items",
  "animation",
  "animation-delay",
  "animation-direction",
  "animation-duration",
  "animation-fill-mode",
  "animation-iteration-count",
  "animation-name",
  "animation-play-state",
  "animation-timing-function",
  "background",
  "background-color",
  "border",
  "border-bottom",
  "border-color",
  "border-radius",
  "border-style",
  "border-top",
  "border-width",
  "bottom",
  "box-shadow",
  "box-sizing",
  "color",
  "cursor",
  "display",
  "filter",
  "flex",
  "flex-basis",
  "flex-direction",
  "flex-grow",
  "flex-shrink",
  "flex-wrap",
  "font",
  "font-family",
  "font-size",
  "font-weight",
  "gap",
  "grid",
  "grid-template-columns",
  "grid-template-rows",
  "height",
  "inset",
  "justify-content",
  "left",
  "letter-spacing",
  "line-height",
  "margin",
  "margin-bottom",
  "margin-left",
  "margin-right",
  "margin-top",
  "max-height",
  "max-width",
  "min-height",
  "min-width",
  "opacity",
  "outline",
  "overflow",
  "padding",
  "padding-bottom",
  "padding-left",
  "padding-right",
  "padding-top",
  "pointer-events",
  "position",
  "right",
  "text-align",
  "text-decoration",
  "text-transform",
  "top",
  "transform",
  "transform-origin",
  "transition",
  "transition-delay",
  "transition-duration",
  "transition-property",
  "transition-timing-function",
  "visibility",
  "white-space",
  "width",
  "z-index",
] as const;

export const DEFAULT_SANITIZATION_OPTIONS: SanitizationOptions = {
  allowedAtRules: ["media", "supports", "layer"],
  allowedProperties: [...DEFAULT_ALLOWED_PROPERTIES],
  allowDataUrls: false,
};
